### PR TITLE
WIP: tests: Add basic GNOME Contacts test

### PR DESCRIPTION
**Pull request by pwithnall**
This launches GNOME Contacts, creates a contact, relaunches the app to
check storage is persistent, then deletes it.

Signed-off-by: Philip Withnall <withnall@endlessm.com>

https://phabricator.endlessm.com/T25684

### CODE REVIEW

**Comment by pwithnall** [comment]
Test run happening [here](https://openqa.endlessm.com/tests/overview?distri=eos&version=master&build=190422-225637&groupid=1), though I suspect it will fail due to FBE failures early on in the OpenQA sequence.

**Comment by wjt** [comment]
Closing this because we can't push a branch named `staging` while branches of the form `staging/*` exist; I've copied this branch to `pwithnall/gnome-contacts`

**Comment by pwithnall** [comment]
(Context: https://phabricator.endlessm.com/T25430#723607)

**Comment by pwithnall** [comment]
Finally updated this in #78.

**Pull request closed without merging**
