### PR TITLE
tests: Add UI test for extra-languages setting

### PR DESCRIPTION
**Pull request by mazen-asef**
Add a test that verifies that gnome-software is indeed showing
the added extra-languages apps on the overview.

https://phabricator.endlessm.com/T28469

### CODE REVIEW

**Comment by mazen-asef** [comment]
Latest test: https://openqa.endlessm.com/tests/46373#step/gnome_software_extra_languages/12

**Comment by pwithnall** [comment]
What’s with the green highlight box in `needles/gnome_software_extra_languages.png`? That doesn’t look right.

Otherwise this looks good to me. :-D

**Comment by mazen-asef** [comment]
@pwithnall Isn't this the way to match a specific part of the screen? I did that in order to not get a fail if the search sorts different stuff on the apps that doesn't not match the name, but the description and etc.etc. Am I wrong? hahaha

Of course, the search results may vary when we push different apps that would fall on top of that list, but...

**Comment by pwithnall** [comment]
> @pwithnall Isn't this the way to match a specific part of the screen? I did that in order to not get a fail if the search sorts different stuff on the apps that doesn't not match the name, but the description and etc.etc. Am I wrong? hahaha

Sort of. Unless I’m misinterpreting the diff in github, there’s actually a green rectangle in the PNG file, which is wrong — it should be an unmodified screenshot of the screen, and the JSON file should contain the coordinates of the region to match (which I think it does).

Did you save the screenshot from the OpenQA editor on openqa.endlessm.com, with the green overlay rectangle present?

> Of course, the search results may vary when we push different apps that would fall on top of that list, but...

That’s a problem for the future; I can’t think of a way around that. :-)

**Comment by mazen-asef** [comment]
Yeah, it was saved with the rectangle overlay present - should it not have any saved?

**Comment by pwithnall** [comment]
Nope, it should be a screenshot from OpenQA without any of the needles or overlays selected, i.e. exactly how you’d see the screen if you were running the test yourself manually.

**Comment by pwithnall** [comment]
(See how the other PNGs in the `needles` directory look.)

**Comment by pwithnall** [comment]
The PNG looks better now, but why is it listing the English version twice (once above the `pt_BR` version, and once below)?

**Comment by mazen-asef** [comment]
I thought this was not yet solved, but as per https://phabricator.endlessm.com/T28198 it seems to be. This is a 11/22 master base image, so this theorethically has been fixed...

**Comment by mazen-asef** [comment]
Yeah, it seems this was just a hiccup on my testing, instead of testing on eos3.7 I was testing on master, which has a duplicated animals app.

**Pull request merged**
