### PR TITLE
needles: Update needle for control-center's user panel

### PR DESCRIPTION
**Pull request by uajain**
The current needle is quite as evident from the GTK theme.
Update to the latest visual of gnome-control-center-3.34
user panel. This will verify the parental control setup.

https://phabricator.endlessm.com/T27552

Name of Test which  failed in regard to this PR: `parental_controls_setup`

### CODE REVIEW

**Comment by uajain** [comment]
First contribution: Opening the PR after @wjt explained me how to update needles for failing test. This will not fix the actual failure (which is happening due to flatpak-install polkit regression) but I found that the current needle is very old.

**Comment by wjt** [comment]
This looks fine. In theory, you could follow the instructions on https://phabricator.endlessm.com/w/software/build/openqa/triaging-test-failures/ to actually test it. Unfortunately it seems @mazen-asef is using the `staging` branch at the moment.

**Comment by uajain** [comment]
> Looks good to merge once the `staging` branch is free and you’ve tested it.

Ah, there are quite  a few needles update. Was testing on `staging` earlier but hit the flatpak-install-polkit regression eventually. WIP work is saved on [this branch](https://github.com/endlessm/eos-openqa-tests/commits/uajain/parental_controls_setup).

**Comment by pwithnall** [comment]
I think that this has unfortunately been invalidated by the recent shell rebase landing, so let’s close this so that things don’t hang around in an open state forever. Unfortunately it seems that OpenQA changes need to be merged within (roughly) a day in order to be useful, which is a bit of a pain for everyone, but :shrug:.

**Pull request closed without merging**
