### PR TITLE
Await LibreOffice splash screen; wait a bit longer

### PR DESCRIPTION
**Pull request by wjt**
LibreOffice seems to take more than 10 seconds to start, which is a bit sad but there we go.

Add a non-fatal check for its splash screen, and increase its timeout.

### CODE REVIEW

**Comment by wjt** [comment]
Running, I hope, on https://openqa.dev.endlessm.com/tests/overview?distri=eos&version=master&build=181130-003125&groupid=1

**Comment by pwithnall** [comment]
LGTM once the test run passes.

Why ‘I hope’?

**Comment by wjt** [comment]
Because at the time I wrote that comment, no test had got far enough that I could check the commit hash in the openQA debug log

**Comment by wjt** [comment]
It doesn't work. It's almost as if the LibreOffice window is starting minimized…

**Comment by pwithnall** [comment]
Hmm. I’ve seen that as a test failure a few times: LO is listed in the Shell bottom bar as running, but no window is visible despite waiting for several minutes. I haven’t found the time to investigate it before though, and have never managed to incidentally reproduce it on a normal VM (in the course of other work, so without really trying to reproduce).

Could this be related to the other bug we saw where the toolbars were missing? Perhaps it’s decided that some “start in headless mode” preference has been set?

**Comment by wjt** [comment]
Closing because we can't push a branch named `staging` while branches named `staging/*` exist; I've copied the branch to `wait-longer-for-libreoffice`.

**Pull request closed without merging**
