### PR TITLE
Update desktop_shortcuts needles

### PR DESCRIPTION
**Pull request by wjt**
Builds on https://github.com/endlessm/eos-openqa-tests/pull/100.

The bit I was interested in (the LibreOffice icon appearing) works. But there's a bit more of the test to go.

https://phabricator.endlessm.com/T27988

### CODE REVIEW

**Comment by wjt** [comment]
Okay, removed this from staging. I tried to add this thing to change some LibreOffice settings, but then the FBE test failed to pass because clicking Next on the first page had no effect, so I gave up in a huff.

But https://openqa.endlessm.com/tests/63922 shows desktop_shortcuts getting rather further than before, and in particular verifying the linked ticket has resolved itself by miraculous means.

**Comment by pwithnall** [comment]
> but then the FBE test failed to pass because clicking Next on the first page had no effect, so I gave up in a huff.

Retry it three times and it typically passes, I think. It seems to completely ignore input and nobody has managed to find time to diagnose it yet (still).

**Comment by wjt** [comment]
Truly I tell you that last week, before the rooster crowed, openQA denied me three times.

Happily, today it passed, including this new step to disable some LibreOffice stuff, https://openqa.endlessm.com/tests/63978, so progress can be made.

**Comment by wjt** [comment]
grr, now it's failing because LibreOffice's 4-star rating is displayed nondeterministically in the search results, cool cool

**Comment by pwithnall** [comment]
I will be ecstatic to review this once it is no longer marked as WIP.

**Comment by pwithnall** [comment]
Any progress on this?

**Comment by wjt** [comment]
No, but https://openqa.endlessm.com/tests/65025 shows this test getting further than it used to, and https://openqa.endlessm.com/tests/65007 shows the thing to disable LibreOffice's tip of the day running successfully, so if I just rebrand the top commit as not a WIP perhaps we should land it?

**Comment by pwithnall** [comment]
> so if I just rebrand the top commit as not a WIP perhaps we should land it?

Yes, the perfect is definitely the enemy of the good with OpenQA, I think.

**Pull request merged**
